/*
* This Java source file was generated by the Gradle 'init' task.
*/
package speech;    
import java.util.* ; 
// import marytts . modules . synthesis . voice . * ;
import marytts.MaryInterface;
import marytts.modules.synthesis.Voice;
import javax.sound.sampled.AudioInputStream;
import marytts.LocalMaryInterface;
import marytts.util.data.audio.AudioPlayer;
public class App   {        
    // variable to hold the text that will be audible  
  
    public static void main( String args[ ] )        
    {        
        try {
        // creating an object of the class TexttoSpeech  
        MaryInterface marytts = new LocalMaryInterface();
        Set<String> voices = marytts.getAvailableVoices();

        System.out.println(marytts.getAvailableVoices());
        //marytts.setLocale(Locale.FRENCH);
        //marytts.setVoice("enst-camille-hsmm");
        AudioInputStream audio = marytts.generateAudio("1");
        AudioPlayer player = new AudioPlayer(audio);
        player.start();
        player.join();
    } catch (Exception e) {
        e.printStackTrace();
    }
    }        
}   